apiVersion: v1
kind: Service
metadata:
  name: node-lb
spec:
  type: LoadBalancer
  selector:
    name: Frontend
    project: Expense
    comp: frontend
    environ: dev
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80  
    nodePort: 32761