apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    name: Frontend
    project: Expense
    comp: frontend
    environ: dev
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80 