kind: Pod
apiVersion: v1
metadata:
  name: nginxconfig
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: nishithkube
    # env:
    # - name: jfrog
    #   valueFrom:
    #     configMapKeyRef:
    #       name:  nishithkube
    #       key: course
    # - name: traine
    #   valueFrom:
    #     configMapKeyRef:
    #       name: nishithkube
    #       key: trainer