kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100m"
        mem: "128Mi"
      limits:
        cpu: "100m"
        mem: "128Mi"